### ISSUE TITLE
make on Windows fails for README.md 

### ISSUE THREAD

**Issue by tomk3003** [oetiker/net-ldap-spnego#1]
`Running make for O/OE/OETIKER/Net-LDAP-SPNEGO-0.1.6.tar.gz
cp lib/Net/LDAP/SPNEGO.pm blib\lib\Net\LDAP\SPNEGO.pm
"C:\Progs\Perl5222\perl\bin\perl.exe" -IC:/Progs/Perl5222/cpan/build/Net-LDAP-SP
NEGO-0.1.6-AVH3RF/3rd/lib/perl5 -MPod::Markdown::Github -e 'binmode(STDOUT, ":ut
f8");Pod::Markdown::Github->new->filter(qlib/Net/LDAP/SPNEGO.pm)' > README.md
Can't find string terminator "'" anywhere before EOF at -e line 1.
dmake.exe:  Error code 130, while making 'README.md'
dmake.exe:  'README.md' removed.`

I think this can be written better (and Windows cmd shell conform) as:

`... -e "'binmode(STDOUT, q(:utf8));Pod::Markdown::Github->new->filter(q(lib/Net/LDAP/SPNEGO.pm))"`

single quotes and curlies will not play nice with the limited Windows command line

**Comment by oetiker** [comment]
yey :) will you make a PR ? you you use this on window ???

**Comment by tomk3003** [comment]
Perhaps. First I'd have to look at how to do that and second I'd like to have the module working in the first place.

I have found and fixed another bug (will file an issue shortly) , but still cannot get the example to work under Windows. I'm still debugging.

**Comment by oetiker** [comment]
note that I have found that one of our AD servers is also unwilling to play ball if the client is on a windows box in the same domain ...

**Comment by tomk3003** [comment]
I have found the main issue. Our AD server wants to have TLS enabled. I did that and now the connection works. But I am prompted for a password. When I give the login information my groups are shown correctly. Is this planned behaviour? I thought this should be SSO?

**Comment by oetiker** [comment]
yes, it has the potential to be sso ... but that depends on your browser settings ... in general you have to put the server into the trusted zone of your clients internet configuration settings

**Comment by tomk3003** [comment]
It seems to work now with SSO. 
could it be that the login dialog was triggered by setting debug to 3? I reset it to 0 and deleted the saved NTLM password and now it seems to work without prompt. Looks fine now.

I'll look into pull requests tomorrow.

**Comment by oetiker** [comment]
I am not aware that the perl server side is able to influence the client as to weather it does sso or not ...

**Comment by tomk3003** [comment]
I just tried a new connection with another URL (lokal IP address instead of 127.0.0.1) and got the password dialog again. I just pressed "Cancel" and did a reload and now it worked. Then I closed down the server and closed IE, restarted both and it still works. So only the first connect seems to trigger the password prompt.

Strange...

**Comment by tomk3003** [comment]
Hmm, maybe this has something to with the certificate exchange on first connect? Would this be logged in the Net::LDAP debug output?

**Comment by oetiker** [comment]
there is no certificate exchange between webbrowser and perlmodule ...

**Comment by tomk3003** [comment]
I thought about the connection between module and LDAP server in case of a TLS connection.
I don't have the time now, but I will try to find out what causes that first dialog to appear.

**Comment by oetiker** [comment]
there is a tls LDAP connection but it is terminated at the perl server ... the browser does not see this

**Comment by tomk3003** [comment]
Found and fixed it. The problem lies in the handshake of browser and perl used in the example as well as in Mojolicious::Plugin::SPNEGO. My IE (11) sends the Type 1 Token immediately on the first request. So there is no need for a status 'init' and a 401 response. You can proceed to 'expectType1' immediately.

I will make a PR for Mojolicious::Plugin::SPNEGO. The Net::LDAP::SPNEGO synopsis and example should be revised too.

**Comment by oetiker** [comment]
fixed via #2
